### ISSUE TITLE
uefi and legacy installation

### ISSUE THREAD

**Issue by abdullah-erturk** [cregx/wim-backup#6]
I edited the action.bat file for both uefi and legacy installation, there is no problem in the backup part, but after selecting the mbr or gpt of the disk in the restore part, it goes back to the mbr or gpt selection of the disk. After selecting mbr or gpt for the second time, it starts to restore the wim file, but it fails when it reaches 99% level. Can you help me edit the action.bat file to suit both uefi and legacy installation?

action bat file is attached.

Additionally, according to this edited bat file, 2 diskpart.txt files are required.

The first one is diskpart_GPT.txt
The second is diskpart_MBR.txt

The diskpart.txt file already exists in your project, you should recreate it according to the gpt and mbr disk structure.

Take these parts into consideration when doing your tests.

Since github does not allow bat files, I uploaded the action.bat file with the txt extension.

I'm looking forward to your answer.

Thank you very much in advance
[action.bat.txt](https://github.com/cregx/wim-backup/files/15340915/action.bat.txt)

**Comment by cregx** [comment]
Hi, I couldn't find any obvious errors in your batch code. However, I have to admit that I am not an expert in batch programming. ;-)

If the error occurs during the restore process, especially in the DISM apply-image command at 99%, I would focus on that point. It might be helpful to run the CMD from the GUI and try the restore manually from there. This way, you might be able to find out more details about the problem.

A small suggestion: if the error - which I find hard to imagine at the moment - occurs due to a problem in the diskpart section, you could include an `if %errorlevel% neq 0` check after its execution. In the event of an error, you could then terminate further execution with `exit /b %errorlevel%`.

As I said, I have no other ideas at the moment. Good luck!

**Comment by cregx** [comment]
@abdullah-erturk: I hope you are doing well.

I wanted to follow up and ask if you were able to find a solution to the issue you mentioned regarding the action.bat file for both UEFI and legacy installations. If so, I would be happy to incorporate the solution into the project so others can benefit from it.

Regardless, I am considering closing this issue for now to prevent it from remaining open unnecessarily. Please feel free to reopen it or create a new issue if needed.

Thank you again for your contribution, and I look forward to your response. Best regards.

**Comment by cregx** [comment]
Issue closed due to inactivity.
